name: 'Create Environment File'
description: 'Creates .env file with required environment variables'

inputs:
  sonar_project_key:
    description: 'Sonar Project Key'
    required: true
  sonar_organization:
    description: 'Sonar Organization'
    required: true
  sonar_host_url:
    description: 'Sonar Host URL'
    required: true

runs:
  using: "composite"
  steps:
    - name: Create .env file
      shell: bash
      run: |
        touch .env
        echo "SONAR_PROJECT_KEY=${{ inputs.sonar_project_key }}" >> .env
        echo "SONAR_ORGANIZATION=${{ inputs.sonar_organization }}" >> .env
        echo "SONAR_HOST_URL=${{ inputs.sonar_host_url }}" >> .env
