name: 'Create Environment File'
description: 'Creates .env file with required environment variables'

runs:
  using: "composite"
  steps:
    - name: Create .env file
      shell: bash
      run: |
        touch .env
        echo "SONAR_PROJECT_KEY=${{ secrets.SONAR_PROJECT_KEY }}" >> .env
        echo "SONAR_ORGANIZATION=${{ secrets.SONAR_ORGANIZATION }}" >> .env
        echo "SONAR_HOST_URL=${{ secrets.SONAR_HOST_URL }}" >> .env
