name: 'Create Environment File'
description: 'Creates .env file with required environment variables'

runs:
  using: "composite"
  steps:
    - name: Create .env file
      shell: bash
      run: |
        touch .env
        echo "AWS_ACCOUNT_ID=${{ env.AWS_ACCOUNT_ID }}" >> .env
        echo "AWS_REGION=${{ env.AWS_REGION }}" >> .env
