name: Create Environment File
on:
  workflow_call:

jobs:
  create-env:
    runs-on: ubuntu-latest
    steps:
      - name: Create .env file
        run: |
          touch .env
          echo "SONAR_PROJECT_KEY=${{ secrets.SONAR_PROJECT_KEY }}" >> .env
          echo "SONAR_ORGANIZATION=${{ secrets.SONAR_ORGANIZATION }}" >> .env
          echo "SONAR_HOST_URL=${{ secrets.SONAR_HOST_URL }}" >> .env
