name: Create Environment File
on:
  workflow_call:

jobs:
  create-env:
    runs-on: ubuntu-latest
    steps:
      - name: Create .env file
        run: |
          touch .env
          echo "AWS_ACCOUNT_ID=${{ env.AWS_ACCOUNT_ID }}" >> .env
          echo "AWS_REGION=${{ env.AWS_REGION }}" >> .env
