name: Detekt

on: [pull_request]

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run detekt
        working-directory: HelloWorldFunction
        run: ./gradlew detekt

      - name: Debug - List reports directory
        working-directory: HelloWorldFunction
        run: |
          ls -la build/reports/
          ls -la build/reports/detekt/
        if: always()

      - name: Upload SARIF files
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: HelloWorldFunction/build/reports/detekt/detekt.sarif
